# Site settings
title: Phapi Framework
description: "Phapi is a PHP based framework aiming at rapid and simplified API development as well as focusing at performance and keeping the code base small and simple."
baseurl: ""
url: "http://phapi.github.io"

timezone: Europe/Stockholm
markdown: redcarpet
highlighter: none
paginate: 5
paginate_path: "/blog/page:num/"

pages_list:
  Blog: '/blog/'
  Documentation: '/docs/'
  Contribute: '/docs/contributions/'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "docs"
